### ISSUE TITLE
Helm Chart / documentation inconsistency

### ISSUE THREAD

**Issue by MatthiasLohr** [cbeneke/helm-charts#10]
Hey,

first: Thanks for your great work with the fip controller!

I'm trying to get it running with your helm chart with the following config:
```
configInline:
  hcloud_floating_ips: "111.222.333.444/32"
secretInline:
  HCLOUD_API_TOKEN: "thatsmysecret"
```

I'm getting the following error from helm:
```
Error: UPGRADE FAILED: template: hcloud-fip-controller/templates/secret.yaml:9:33: executing "hcloud-fip-controller/templates/secret.yaml" at <2>: wrong type for value; expected string; got map[string]interface {}
```

This "works" in the sense that the error is gone:
```
configInline:
  hcloud_floating_ips: "111.222.333.444/32"
secretInline: |
  HCLOUD_API_TOKEN: "thatsmysecret"
```

But I still get an error "IP address not allocated". IP address is registered with Hetzner and added to all machines in the cluster.
