### ISSUE TITLE
Secret not created by helm chart

### ISSUE THREAD

**Issue by vitobotta** [cbeneke/helm-charts#4]
Hi, I am testing the chart and found that the pods still require a secret named "fip-controller-secrets", which is not created by the chart so I have to create it manually. Am I missing something? Thanks

**Comment by vitobotta** [comment]
After creating the secret, the pod doesn't start, and complains like this:

```
could not initialise controller: controller config invalid: required configuration options not configured:
```

However it doesn't list the required config settings that are missing.

This is the values.yaml I am using:

```yaml
cat > /tmp/fip-controller.yaml <<EOF
deploymentKind: Deployment
replicaCount: 1
configInline:
  hcloud_floating_ips:
    - "<ip>"
  hcloud_api_token: "<token>"
  lease_duration: 5
  node_address_type: "internal"
EOF
```

Then I install it like this:

```bash
helm upgrade --install --namespace hcloud-fip-controller-1 -f /tmp/fip-controller.yaml hcloud-fip-controller-1 cbeneke/hcloud-fip-controller
```

Thanks
